# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: 'SelfHostedAgent'

steps:
- checkout: self

- task: Maven@3
  inputs:
    mavenPomFile: 'StudentGradeApp/pom.xml'
    mavenOptions: '-Xmx3072m'
    options: '-DskipTests'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    goals: 'package'
